### ISSUE TITLE
Publishing on crates.io?

### ISSUE THREAD

**Issue by amousset** [1aim/mail#1]
Hello,

Do you plan to publish these email crates on crates.io?

**Comment by rustonaut** [comment]
Yes, the plan is to publish it soonish (preferable before rustfest).

I did some cleanup work, but it did not yet extend to the template part (or more correctly the cleanup there is not completely done and partially not upstream, yet).

Also I might put many of the parts back into a single repository, most of the reasons why it was split up don't really apply anymore. 

Lastly someone else has the `mail` create name on `crates.io` (and doesn't intend to give it up) so sadly some renaming has to be.

**Comment by amousset** [comment]
Ok, thank you for your answer!

**Comment by RalfJung** [comment]
This seems to have happened?

**Comment by rustonaut** [comment]
Yes, there will be a blog post announcing it consisting of 3 parts:

1. a bit about mail in general
2. a bit about the library
3. a step by step "tutorial" covering a simple use case of 
    creating a mail from handlebars template(s), adding some
    headers and then sending it over a `MSA` (e.g. `smtp.gmail.com`)

The first 2 parts already have been written (but someone needs to
review them, it's just that the someone has currently no time) the
3rd will follow sone.

Also as a side note, while it's already usable it slightly thin in two areas:

1. Documentation which goes above the most basic "that this" rust doc, i.e. some better examples,
    better module doc and README.   Also explaining _why_ some of the less usual thinks are as
    they are.
2. More tests, there are ~200 or so but that still kind little, especially there was a more complex end-2-end
    integration test which I accidentally dropped when doing a large refactoring.

**Comment by TLATER** [comment]
The crate looks to have been published: https://crates.io/crates/mail - shouldn't this issue be closed?

**Comment by rustonaut** [comment]
Thanks for reminding me, I wanted to keep it open until I had at last published 2 of the blog posts and then forgot about this issue as I had many other thinks to do. So, it's closed now.
