### ISSUE TITLE
Confusing UX as compared to lettre

### ISSUE THREAD

**Issue by Dowwie** [1aim/mail#10]
Your mail library may offer more features than [lettre](https://github.com/lettre/lettre) but the user experience is more complex.  What are your thoughts on redesigning the public api?

**Comment by rustonaut** [comment]
Thanks for the feedback, I agree that the current situation is not perfectl.

Nevertheless the API basic  isn't  bad, it's just that it has a lot of other parts, which make it hard to see how to use it from just taking a look at the API doc. It definetly needs more examples. (There are also the mail blog posts, the 3 part adds a example from creating a mail from a handlebars template and sending it through smtp, explaining in more detail the different steps. It's not yet officially published as it needs prof reading and I still have to link in (and publish to github) the example repo. Through you can take a preview here: https://backend.pages.1aim.io/blog/post/004-mail-3-example/. Please do _not_ re-post the link, when it's ready to be published and announced it will be on https://blog.1aim.com/.)

The problem with the a API which is similar to lettr is that it is incompatible with some of the thinks the `mail` crate provide. _But the `mail` crate is meant as a building blog_. So writing a lettre style API which internally uses the mail crate is totally possible. 

Conclusions => 
1. I should add crate which provides a "simple" api/facade over the mail crates.
2. I should consider hiding some of the less relevant methods behind extension trait.
3. I should add some of the examples to the API doc.

Lastly there are some rough edges on the current API which can (and will) be fixed on it, like for example
providing some more helper methods for creating `Resources` instances etc.

**Comment by rustonaut** [comment]
I'm closing this in favor of issues #11, #12 and #13 (but will link back to this from the issues).
