### ISSUE TITLE
"mail_from_template" link on crates.io goes 404

### ISSUE THREAD

**Issue by RalfJung** [1aim/mail#2]
On https://crates.io/crates/mail, the link to `mail_from_template` points to https://github.com/1aim/mail/blob/master/examples/mail_from_template/main.rs, which shows an error 404.

**Comment by rustonaut** [comment]
The problem is that if you make the links work on `github` with a relative path they won't work on `crates.io` and `docs.rs` if you make them work on `docs.rs` they won't work on github... I think I will hard code the links to either point to `github` or  `docs.rs` but then I have to update them with every release ¯\_(ツ)_/¯.

**Comment by RalfJung** [comment]
Is this something that could be fixed on crates.io?

**Comment by rustonaut** [comment]
What basically would be needed is a link which can change dependent on where the README is shown:
1. on github -> use relative link to get thinks like selected branche etc. right
2. on cargo.io/docs.rs -> use a link to docs.rs src view of the example in the uploaded crate with the right version

To some degree this can be done today:
1. Have the README with relative links.
2. Before publishing copy the README (e.g. to README_crates_io.md) replace links with links
    to the docs.rs sites which will be created when publishing
3. Point the `readme` field in `Cargo.toml` to the alt readme (e.g. `README_crates_io.md`)
4. Publish
5. Remove alt README from wip branch as it will get out of sync?

The think is without a tool to do so for you this is way to annoying. But then some little
script might be enough and given that  I want to write a script for publishing anyway
(to e.g. force `mail` to be updated if any dependency is updated) I might just include that.

Until then I think I will go with just hard coding the link to the github (source view of master branch),
and maybe add a warning add the begin of the example files.

**Comment by rustonaut** [comment]
For now I used hard links to github master.

Until I have some "prepare for publish"/"publishing" script it will point to github master.
Afterwards it can be changed to point to a more specific github branch.
