### ISSUE TITLE
Fails to compile on latest rust nightly

### ISSUE THREAD

**Issue by TLATER** [1aim/mail#3]
I'm trying to use this crate to send mails through my rocket-based web server - rocket requires rust-nightly for some nice macro syntax. Unfortunately it seems this crate can't compile using rust-nightly.

My system information:

```
Default host: x86_64-unknown-linux-gnu

nightly-x86_64-unknown-linux-gnu (directory override for '/home/tlater/Documents/Projects/tlaternet')
rustc 1.34.0-nightly (852701ad6 2019-02-01)
```

This is the error I get:

```
   Compiling openssl-sys v0.9.40
   Compiling crossbeam-epoch v0.7.1
   Compiling mail-internals v0.2.0
   Compiling openssl v0.10.16
   Compiling native-tls v0.2.2
error[E0034]: multiple applicable items in scope
  --> /home/tlater/.cargo/registry/src/github.com-1ecc6299db9ec823/mail-internals-0.2.0/src/encoder/encodable.rs:31:14
   |
31 |         self.type_id() == TypeId::of::<T>()
   |              ^^^^^^^ multiple `type_id` found
   |
note: candidate #1 is defined in the trait `encoder::encodable::EncodableInHeader`
  --> /home/tlater/.cargo/registry/src/github.com-1ecc6299db9ec823/mail-internals-0.2.0/src/encoder/encodable.rs:21:5
   |
21 |     fn type_id( &self ) -> TypeId {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: to disambiguate the method call, write `encoder::encodable::EncodableInHeader::type_id(&self)` instead
note: candidate #2 is defined in the trait `std::any::Any`
   = help: to disambiguate the method call, write `std::any::Any::type_id(&self)` instead

error: aborting due to previous error

For more information about this error, try `rustc --explain E0034`.
error: Could not compile `mail-internals`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by TLATER** [comment]
Note that I haven't tried non-nightly rust yet (it won't compile my code anyway...), so this may well be a generic issue.

**Comment by rustonaut** [comment]
Looks like a rust regression or bug allowed compiling ambigues code in
previous rust versions, I will look into it tomorrow.

**Comment by TLATER** [comment]
I suspect [this](https://github.com/rust-lang/rfcs/pull/2523) will be required to do this neatly. Alternatively, the function will just have to be renamed :|

Sorry, I wanted to push a patch, but this is too opinionated for me to do :(

**Comment by rustonaut** [comment]
I will just use UFC-Syntax, the function is only used in the `is` function,
and the error will only appear if you have the trait which defines it and
`Any` in the same scope you call it. Additionally with any stabilising it's
`get_type_id` function as `type_id` there might be no longer any need for
having my own `type_id` function.

**Comment by rustonaut** [comment]
So thinks are fixed and a new patch release was made.
